# Generated by Django 3.2 on 2022-06-13 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='newssettings',
            name='paginator_pages_show',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many additional pages will be shown in paginator', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Paginator pages show'),
        ),
    ]
