# Generated by Django 3.2 on 2022-06-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20220623_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='slug',
        ),
    ]
