# Generated by Django 3.2 on 2022-07-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_auto_20220625_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_feedback_len', models.PositiveIntegerField(default=20, help_text='Minimum length of feedback text')),
                ('max_feedback_len', models.PositiveIntegerField(default=500, help_text='Maximum length of feedback text')),
                ('feedback_email_title', models.CharField(default='Answer on question', max_length=50, verbose_name='Title of email')),
                ('feedback_email', models.TextField(default='<h4>Given answer to your question</h4><br><p>Your question:</p><span>{question}</span><br><p>Answer:</p><span>{answer}</span><p>With love AnimeService team</p>', verbose_name='Feedback email')),
            ],
            options={
                'verbose_name': 'Helper Configuration',
            },
        ),
    ]
