# Generated by Django 3.2 on 2022-07-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_helpersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpersettings',
            name='feedback_email_en',
            field=models.TextField(default='<h4>Given answer to your question</h4><br><p>Your question:</p><span>{question}</span><br><p>Answer:</p><span>{answer}</span><p>With love AnimeService team</p>', null=True, verbose_name='Feedback email'),
        ),
        migrations.AddField(
            model_name='helpersettings',
            name='feedback_email_title_en',
            field=models.CharField(default='Answer on question', max_length=50, null=True, verbose_name='Title of email'),
        ),
        migrations.AddField(
            model_name='helpersettings',
            name='feedback_email_title_uk',
            field=models.CharField(default='Answer on question', max_length=50, null=True, verbose_name='Title of email'),
        ),
        migrations.AddField(
            model_name='helpersettings',
            name='feedback_email_uk',
            field=models.TextField(default='<h4>Given answer to your question</h4><br><p>Your question:</p><span>{question}</span><br><p>Answer:</p><span>{answer}</span><p>With love AnimeService team</p>', null=True, verbose_name='Feedback email'),
        ),
    ]
