# Generated by Django 3.2 on 2022-07-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0008_auto_20220711_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='lang',
            field=models.CharField(default='en', max_length=10, verbose_name='Language'),
        ),
    ]
