# Generated by Django 3.2 on 2022-07-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0009_feedback_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Українськa')], default='en', max_length=10, verbose_name='Language'),
        ),
    ]
