# Generated by Django 3.2 on 2022-06-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220515_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_password_len', models.PositiveIntegerField(default=8, help_text='Minimum password length of user account')),
                ('max_password_len', models.PositiveIntegerField(default=64, help_text='Maximum password length of user account')),
            ],
            options={
                'verbose_name': 'User Configuration',
            },
        ),
    ]
