# Generated by Django 3.2 on 2022-06-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Українськa')], default='en', max_length=10, verbose_name='Language'),
        ),
    ]
