# Generated by Django 3.2 on 2022-07-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220711_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='change_email_en',
            field=models.TextField(default='To verify your new email address pls open url {url}', null=True, verbose_name='Change email title'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='change_email_title_en',
            field=models.CharField(default='Change email', max_length=50, null=True, verbose_name='Title for change email'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='change_email_title_uk',
            field=models.CharField(default='Change email', max_length=50, null=True, verbose_name='Title for change email'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='change_email_uk',
            field=models.TextField(default='To verify your new email address pls open url {url}', null=True, verbose_name='Change email title'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='registered_email_en',
            field=models.TextField(default='Hello {name} you have been registered success. Verify your account {url}', null=True, verbose_name='Change email title'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='registered_email_title_en',
            field=models.CharField(default='Verify account', max_length=50, null=True, verbose_name='Title for registered email'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='registered_email_title_uk',
            field=models.CharField(default='Verify account', max_length=50, null=True, verbose_name='Title for registered email'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='registered_email_uk',
            field=models.TextField(default='Hello {name} you have been registered success. Verify your account {url}', null=True, verbose_name='Change email title'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='reset_email_en',
            field=models.TextField(default='Reset your account password {url}', null=True, verbose_name='Change email title'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='reset_email_title_en',
            field=models.CharField(default='Reset your account password', max_length=50, null=True, verbose_name='Title for reset email'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='reset_email_title_uk',
            field=models.CharField(default='Reset your account password', max_length=50, null=True, verbose_name='Title for reset email'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='reset_email_uk',
            field=models.TextField(default='Reset your account password {url}', null=True, verbose_name='Change email title'),
        ),
    ]
