# Generated by Django 3.2 on 2022-05-24 19:49

import apps.movie.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'ordering': ['wight'], 'verbose_name': 'Quality', 'verbose_name_plural': 'Quality'},
        ),
        migrations.AlterField(
            model_name='episodefile',
            name='file',
            field=models.FileField(upload_to=apps.movie.models.anime_path, validators=[django.core.validators.FileExtensionValidator(['webm', 'mpg', 'ogg', 'mp4', 'mpeg'])]),
        ),
        migrations.AlterField(
            model_name='quality',
            name='wight',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='quality',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='quality',
            name='height',
        ),
    ]
