# Generated by Django 3.2 on 2022-05-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20220524_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='name',
        ),
    ]
