# Generated by Django 3.2 on 2022-05-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quality',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Name'),
        ),
    ]
