# Generated by Django 3.2 on 2022-06-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20220529_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('display', models.BooleanField(default=True, verbose_name='Display')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.TextField(blank=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='anime',
            name='tag_list',
            field=models.ManyToManyField(blank=True, related_name='anime', to='movie.Tag'),
        ),
    ]
