# Generated by Django 3.2 on 2022-06-18 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20220618_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_per_page', models.PositiveSmallIntegerField(default=10, help_text='How many movies will be shown per page', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Movie per page')),
                ('paginator_pages_show', models.PositiveSmallIntegerField(default=3, help_text='How many additional pages will be shown in paginator', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Paginator pages show')),
                ('max_reviews_per_season', models.PositiveSmallIntegerField(default=2, help_text='How many reviews can a user send on an season', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Reviews per season')),
            ],
            options={
                'verbose_name': 'Movie Configuration',
            },
        ),
    ]
