# Generated by Django 3.2 on 2022-06-18 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_moviesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesettings',
            name='max_review_length',
            field=models.PositiveSmallIntegerField(default=500, help_text='Maximum length of review text', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Review length'),
        ),
        migrations.AddField(
            model_name='moviesettings',
            name='min_review_length',
            field=models.PositiveSmallIntegerField(default=20, help_text='Minimum length of review text', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Min Review length'),
        ),
    ]
