# Generated by Django 3.2 on 2022-06-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20220618_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='style/', verbose_name='Background'),
        ),
    ]
