# Generated by Django 3.2 on 2022-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_auto_20220619_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='style',
            field=models.TextField(blank=True, null=True, verbose_name='Style'),
        ),
    ]
