# Generated by Django 3.2 on 2022-06-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_alter_style_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='style',
            field=models.TextField(blank=True, verbose_name='Style'),
        ),
    ]
