# Generated by Django 3.2 on 2022-06-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_alter_style_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Українськa')], default='en', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='anime',
            unique_together={('slug', 'lang')},
        ),
    ]
