# Generated by Django 3.2 on 2022-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_auto_20220624_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('FI', 'Film'), ('SE', 'Serial')], default='SE', max_length=2, verbose_name='Content type'),
        ),
    ]
