# Generated by Django 3.2 on 2022-06-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_moviesettings_new_episode_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesettings',
            name='new_episode_email_title',
            field=models.CharField(default='New Episode {name} #{number}', max_length=50, verbose_name='Title of email'),
        ),
        migrations.AlterField(
            model_name='moviesettings',
            name='new_episode_email',
            field=models.TextField(default='New episode {name} #{number} at our site, Click to watch {url}', verbose_name='New episode email'),
        ),
    ]
