# Generated by Django 3.2 on 2022-06-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_auto_20220630_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesettings',
            name='new_episode_email_en',
            field=models.TextField(default='New episode {name} #{number} at our site, Click to watch {url}', null=True, verbose_name='New episode email'),
        ),
        migrations.AddField(
            model_name='moviesettings',
            name='new_episode_email_title_en',
            field=models.CharField(default='New Episode {name} #{number}', max_length=50, null=True, verbose_name='Title of email'),
        ),
        migrations.AddField(
            model_name='moviesettings',
            name='new_episode_email_title_uk',
            field=models.CharField(default='New Episode {name} #{number}', max_length=50, null=True, verbose_name='Title of email'),
        ),
        migrations.AddField(
            model_name='moviesettings',
            name='new_episode_email_uk',
            field=models.TextField(default='New episode {name} #{number} at our site, Click to watch {url}', null=True, verbose_name='New episode email'),
        ),
    ]
